# Generated by Django 5.2.8 on 2025-12-10 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_autor_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='image',
            field=models.ImageField(null=True, upload_to='imagenes_libros'),
        ),
    ]
