# Generated by Django 5.2.8 on 2025-12-10 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_libro_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='image',
            new_name='imagen',
        ),
    ]
