# Generated by Django 5.2.8 on 2025-12-11 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_rename_image_libro_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='frcha_publicacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
