# Generated by Django 5.2.8 on 2025-12-11 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_libro_frcha_publicacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='frcha_publicacion',
            new_name='fecha_publicacion',
        ),
    ]
