# Generated by Django 5.2.8 on 2025-12-11 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0006_rename_frcha_publicacion_libro_fecha_publicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='fecha_publicacion',
        ),
        migrations.AddField(
            model_name='libro',
            name='anio_publicacion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
